/**
 * AlertApproval — queue of AI-generated draft alerts.
 * Human approval is MANDATORY before any official alert is sent.
 * Shows language tabs (EN/KOK/MR/HI), edit, Approve/Reject with audit trail.
 */
import React, { useState, useEffect, useCallback } from 'react';
import { AnimatedTabs } from '../components/ui/AnimatedTabs.jsx';
import { StatusBadge, RiskBadge } from '../components/ui/StatusBadge.jsx';
import { SkeletonCard, EmptyState, ErrorState } from '../components/ui/States.jsx';
import { getAlerts, approveAlert, rejectAlert } from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';
import { format } from 'date-fns';
import { CheckCircle2, XCircle, Edit2, ShieldAlert, Bot } from 'lucide-react';
import { BorderBeam, ShimmerButton, CardSpotlight } from '../components/inspira/index.js';

const LANG_TABS = [
  { key: 'en',  label: 'EN' },
  { key: 'kok', label: 'KOK' },
  { key: 'mr',  label: 'MR'  },
  { key: 'hi',  label: 'HI'  },
];

function safeFormat(dateVal, fmt = 'dd MMM HH:mm') {
  if (!dateVal) return 'Recently';
  try {
    const d = new Date(dateVal);
    return isNaN(d.getTime()) ? 'Recently' : format(d, fmt);
  } catch {
    return 'Recently';
  }
}

function AlertCard({ alert, onApprove, onReject }) {
  const [activeLang, setActiveLang] = useState('en');
  const [editing, setEditing]       = useState(false);
  const [editText, setEditText]     = useState('');
  const [rejReason, setRejReason]   = useState('');
  const [showReject, setShowReject] = useState(false);
  const [busy, setBusy]             = useState(false);

  const text = alert.translations?.[activeLang] || '(No translation)';

  const handleApprove = async () => {
    setBusy(true);
    await onApprove(alert.id);
    setBusy(false);
  };

  const handleReject = async () => {
    if (!rejReason.trim()) return;
    setBusy(true);
    await onReject(alert.id, rejReason);
    setBusy(false);
    setShowReject(false);
  };

  const isActioned = alert.status === 'approved' || alert.status === 'rejected';

  return (
    <article className="relative rounded-2xl border border-surface-border bg-surface-card p-5 space-y-4 animate-slide-up overflow-hidden">
      {/* Inspira BorderBeam for high-priority pending alerts */}
      {alert.status === 'pending' && (
        <BorderBeam size={220} duration={8} colorFrom="#f59e0b" colorTo="#ef4444" borderWidth={1.5} />
      )}

      {/* Header */}
      <div className="flex flex-wrap items-center gap-2">
        <Bot size={16} className="text-primary-400" aria-hidden />
        <span className="text-xs text-slate-500">Generated by {alert.generated_by}</span>
        <span className="text-xs text-slate-500">·</span>
        <time className="text-xs text-slate-500" dateTime={alert.generated_at || ''}>
          {safeFormat(alert.generated_at)}
        </time>
        <div className="ml-auto flex items-center gap-2">
          <RiskBadge level={alert.risk_level} />
          <StatusBadge status={alert.status} />
        </div>
      </div>

      <div className="flex items-center gap-2 text-sm font-semibold text-slate-200">
        <ShieldAlert size={15} className="text-amber-400" aria-hidden />
        {alert.area} — {alert.hazard_type} risk alert
      </div>

      {/* Language tabs */}
      <AnimatedTabs tabs={LANG_TABS} activeTab={activeLang} onChange={setActiveLang} />

      {/* Alert text (editable) */}
      <div className="relative">
        {editing ? (
          <textarea
            aria-label={`Edit alert text for ${activeLang}`}
            className="w-full min-h-[80px] bg-slate-800 border border-primary-600/50 rounded-xl p-3 text-sm text-slate-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary-400"
            value={editText || text}
            onChange={e => setEditText(e.target.value)}
          />
        ) : (
          <p className="p-3.5 rounded-xl bg-slate-800/70 border border-surface-border text-sm text-slate-200 leading-relaxed font-sans">
            {text}
          </p>
        )}
        {!isActioned && (
          <button
            onClick={() => { setEditing(e => !e); if (!editing) setEditText(text); }}
            className="absolute top-2 right-2 p-1.5 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-700/50 transition-colors cursor-pointer"
            aria-label={editing ? 'Cancel edit' : 'Edit alert text'}
          >
            <Edit2 size={13} aria-hidden />
          </button>
        )}
      </div>

      {/* Audit trail */}
      {alert.status === 'approved' && (
        <div className="flex items-center gap-2 text-xs text-emerald-400 bg-emerald-900/20 border border-emerald-700/30 rounded-xl px-3 py-2">
          <CheckCircle2 size={13} aria-hidden />
          Approved by <strong>{alert.approved_by || 'Authority'}</strong> at {safeFormat(alert.approved_at)}
        </div>
      )}
      {alert.status === 'rejected' && (
        <div className="flex items-center gap-2 text-xs text-red-400 bg-red-900/20 border border-red-700/30 rounded-xl px-3 py-2">
          <XCircle size={13} aria-hidden />
          Rejected — {alert.reject_reason || 'No reason given'}
        </div>
      )}

      {/* Actions */}
      {!isActioned && (
        <div className="flex flex-wrap items-center gap-3 pt-1">
          <ShimmerButton
            onClick={handleApprove}
            disabled={busy}
            shimmerColor="#6ee7b7"
            background="linear-gradient(135deg, rgba(6, 95, 70, 0.95), rgba(4, 120, 87, 0.95))"
            className="px-4 py-2 rounded-xl text-white font-semibold text-xs shadow-md"
          >
            <CheckCircle2 size={14} aria-hidden />
            {busy ? 'Broadcasting...' : 'Approve & Broadcast Alert'}
          </ShimmerButton>

          <button
            onClick={() => setShowReject(r => !r)}
            disabled={busy}
            className="flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold rounded-xl
              bg-red-950/40 text-red-300 border border-red-800/40
              hover:bg-red-900/50 disabled:opacity-50 transition-colors cursor-pointer"
            aria-label="Reject this alert"
          >
            <XCircle size={13} aria-hidden /> Reject Draft
          </button>

          {showReject && (
            <div className="w-full flex gap-2 mt-1">
              <input
                type="text"
                value={rejReason}
                onChange={e => setRejReason(e.target.value)}
                placeholder="Reason for rejection…"
                aria-label="Rejection reason"
                className="flex-1 bg-slate-800 border border-red-700/40 rounded-xl px-3 py-1.5 text-sm text-slate-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-red-400"
              />
              <button
                onClick={handleReject}
                disabled={!rejReason.trim() || busy}
                className="px-3 py-1.5 text-sm rounded-xl bg-red-900/50 text-red-300 border border-red-700/40 hover:bg-red-800/60 disabled:opacity-40 transition-colors"
              >
                Confirm
              </button>
            </div>
          )}
        </div>
      )}
    </article>
  );
}

export default function AlertApproval() {
  const { user } = useAuth();
  const [alerts, setAlerts]   = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(null);
  const [tab, setTab]         = useState('pending');

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await getAlerts();
      setAlerts(res.data);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleApprove = async (id) => {
    const updated = await approveAlert(id, user);
    setAlerts(as => as.map(a => a.id === id ? updated : a));
  };

  const handleReject = async (id, reason) => {
    const updated = await rejectAlert(id, reason);
    setAlerts(as => as.map(a => a.id === id ? updated : a));
  };

  const visible = alerts.filter(a => tab === 'all' || a.status === tab);

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Human-in-the-loop notice — always visible */}
      <div className="flex items-start gap-3 p-4 rounded-2xl bg-amber-900/20 border border-amber-700/30">
        <ShieldAlert size={20} className="text-amber-400 shrink-0 mt-0.5" aria-hidden />
        <div>
          <p className="text-sm font-semibold text-amber-300">Human approval required</p>
          <p className="text-xs text-amber-400/80 mt-0.5">
            No alert is sent to residents until an authority officer reviews and approves it here.
            AI drafts are suggestions only.
          </p>
        </div>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-2xl font-bold text-slate-100">Alert Approval Queue</h1>
        <AnimatedTabs
          tabs={[
            { key: 'pending',  label: `Pending (${alerts.filter(a => a.status === 'pending').length})` },
            { key: 'approved', label: 'Approved' },
            { key: 'rejected', label: 'Rejected' },
            { key: 'all',      label: 'All' },
          ]}
          activeTab={tab}
          onChange={setTab}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* LHS: Alert queue (8 cols) */}
        <div className="lg:col-span-8 space-y-4">
          {error
            ? <ErrorState message={error} onRetry={load} />
            : loading
              ? <div className="space-y-4">{[...Array(3)].map((_,i) => <SkeletonCard key={i} />)}</div>
              : visible.length === 0
                ? <EmptyState title="No alerts" message="No AI-generated alerts in this category." />
                : (
                  <div className="space-y-4">
                    {visible.map(a => (
                      <AlertCard key={a.id} alert={a} onApprove={handleApprove} onReject={handleReject} />
                    ))}
                  </div>
                )
          }
        </div>

        {/* RHS: Broadcast Gateway & Safety Checklist (4 cols) */}
        <div className="lg:col-span-4 space-y-5">
          {/* Multi-Channel Broadcast Infrastructure */}
          <div className="rounded-2xl border border-surface-border bg-surface-card p-5 space-y-4 shadow-sm">
            <h3 className="text-sm font-semibold text-slate-100 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
              Broadcast Gateways Status
            </h3>
            
            <div className="space-y-3 text-xs">
              <div className="flex items-center justify-between p-2.5 rounded-xl bg-slate-900/60 border border-surface-border/60">
                <div>
                  <div className="font-medium text-slate-200">Goa Telecom Cell Broadcast</div>
                  <div className="text-[11px] text-slate-500">CAP 1.2 Protocol · Tower Geo-fencing</div>
                </div>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-950/60 text-emerald-400 border border-emerald-800/40">
                  Ready
                </span>
              </div>

              <div className="flex items-center justify-between p-2.5 rounded-xl bg-slate-900/60 border border-surface-border/60">
                <div>
                  <div className="font-medium text-slate-200">SMS Push Gateway</div>
                  <div className="text-[11px] text-slate-500">1,420 Subscribed Households</div>
                </div>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-950/60 text-emerald-400 border border-emerald-800/40">
                  99.8% Up
                </span>
              </div>

              <div className="flex items-center justify-between p-2.5 rounded-xl bg-slate-900/60 border border-surface-border/60">
                <div>
                  <div className="font-medium text-slate-200">Public Acoustic Sirens</div>
                  <div className="text-[11px] text-slate-500">Patto, Ribandar, Panaji Jetty</div>
                </div>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-cyan-950/60 text-cyan-400 border border-cyan-800/40">
                  4/4 Armed
                </span>
              </div>
            </div>
          </div>

          {/* Responsible AI Compliance Gate */}
          <div className="rounded-2xl border border-surface-border bg-surface-card p-5 space-y-3.5 shadow-sm">
            <h3 className="text-sm font-semibold text-slate-100 flex items-center gap-2">
              <ShieldAlert size={16} className="text-amber-400" />
              SOP Approval Checklist
            </h3>
            <ul className="space-y-2 text-xs text-slate-300">
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 font-bold">✓</span>
                <span>Mandatory Human Sign-off verified with officer ID</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 font-bold">✓</span>
                <span>Multi-lingual parity verified (Konkani, Marathi, Hindi, English)</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 font-bold">✓</span>
                <span>Evacuation route coordinates verified safe from active inundation</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 font-bold">✓</span>
                <span>Zero real citizen PII transmitted in public alert packets</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
